from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(750, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(750, 480))
        Form.setMaximumSize(QtCore.QSize(750, 480))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Downloads/icons8-retro-tv-90.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(0.99999)
        self.headerLabel = QtGui.QLabel(Form)
        self.headerLabel.setGeometry(QtCore.QRect(210, 130, 361, 131))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Slab"))
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.headerLabel.setFont(font)
        self.headerLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.headerLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.headerCaptionText = QtGui.QLabel(Form)
        self.headerCaptionText.setGeometry(QtCore.QRect(290, 220, 181, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Fira Sans Compressed"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.headerCaptionText.setFont(font)
        self.headerCaptionText.setStyleSheet(_fromUtf8("color: rgb(126, 126, 126);"))
        self.headerCaptionText.setObjectName(_fromUtf8("headerCaptionText"))
        self.versionLabel = QtGui.QLabel(Form)
        self.versionLabel.setGeometry(QtCore.QRect(520, 160, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(16)
        self.versionLabel.setFont(font)
        self.versionLabel.setObjectName(_fromUtf8("versionLabel"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 270, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 300, 291, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 370, 121, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(30, 380, 701, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 390, 711, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "About Show Sort.", None))
        self.headerLabel.setText(_translate("Form", "Show Sort.", None))
        self.headerCaptionText.setText(_translate("Form", "Sorting TV Shows made effortless...", None))
        self.versionLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400; color:#990000;\">1.0</span></p></body></html>", None))
        self.label.setText(_translate("Form", "Author: Labeeb Latheef", None))
        self.label_2.setText(_translate("Form", "labeebklatif@gmail.com", None))
        self.label_3.setText(_translate("Form", "Disclaimer", None))
        self.label_4.setText(_translate("Form", "  This Tool is specially developed for sorting TV Shows into their seasons and respective\n"
" episodes. This Tool may or may not be used for sorting other type of documents in which case \n"
" the author cannot guarantee the result. All rights reserved by the author.", None))

