from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(750, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(750, 480))
        Form.setMaximumSize(QtCore.QSize(750, 480))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Downloads/icons8-retro-tv-90.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(0.99999)
        self.headerLabel = QtGui.QLabel(Form)
        self.headerLabel.setGeometry(QtCore.QRect(30, 14, 241, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Slab"))
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.headerLabel.setFont(font)
        self.headerLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.headerCaptionText = QtGui.QLabel(Form)
        self.headerCaptionText.setGeometry(QtCore.QRect(70, 64, 181, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Fira Sans Compressed"))
        font.setPointSize(10)
        self.headerCaptionText.setFont(font)
        self.headerCaptionText.setStyleSheet(_fromUtf8("color: rgb(126, 126, 126);"))
        self.headerCaptionText.setObjectName(_fromUtf8("headerCaptionText"))
        self.versionLabel = QtGui.QLabel(Form)
        self.versionLabel.setGeometry(QtCore.QRect(270, 20, 56, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(16)
        self.versionLabel.setFont(font)
        self.versionLabel.setObjectName(_fromUtf8("versionLabel"))
        self.titleTextBox = QtGui.QLineEdit(Form)
        self.titleTextBox.setGeometry(QtCore.QRect(190, 100, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.titleTextBox.setFont(font)
        self.titleTextBox.setCursorPosition(0)
        self.titleTextBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleTextBox.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.titleTextBox.setObjectName(_fromUtf8("titleTextBox"))
        self.titleLabel = QtGui.QLabel(Form)
        self.titleLabel.setGeometry(QtCore.QRect(80, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet(_fromUtf8(""))
        self.titleLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.targetDirectoryLabel = QtGui.QLabel(Form)
        self.targetDirectoryLabel.setGeometry(QtCore.QRect(30, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.targetDirectoryLabel.setFont(font)
        self.targetDirectoryLabel.setObjectName(_fromUtf8("targetDirectoryLabel"))
        self.targetCheckBox = QtGui.QCheckBox(Form)
        self.targetCheckBox.setEnabled(True)
        self.targetCheckBox.setGeometry(QtCore.QRect(160, 180, 151, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        self.targetCheckBox.setFont(font)
        self.targetCheckBox.setIconSize(QtCore.QSize(12, 12))
        self.targetCheckBox.setCheckable(True)
        self.targetCheckBox.setChecked(True)
        self.targetCheckBox.setObjectName(_fromUtf8("targetCheckBox"))
        self.tagetDirectoryCustomTextBox = QtGui.QLineEdit(Form)
        self.tagetDirectoryCustomTextBox.setEnabled(True)
        self.tagetDirectoryCustomTextBox.setGeometry(QtCore.QRect(400, 180, 231, 31))
        self.tagetDirectoryCustomTextBox.setPlaceholderText(_fromUtf8(""))
        self.tagetDirectoryCustomTextBox.setObjectName(_fromUtf8("tagetDirectoryCustomTextBox"))
        self.targetBrowseBtn = QtGui.QPushButton(Form)
        self.targetBrowseBtn.setGeometry(QtCore.QRect(640, 180, 71, 29))
        self.targetBrowseBtn.setObjectName(_fromUtf8("targetBrowseBtn"))
        self.targetDirectoryCustomLabel = QtGui.QLabel(Form)
        self.targetDirectoryCustomLabel.setGeometry(QtCore.QRect(340, 180, 56, 31))
        self.targetDirectoryCustomLabel.setObjectName(_fromUtf8("targetDirectoryCustomLabel"))
        self.searchDirectoryCustomTextBox = QtGui.QLineEdit(Form)
        self.searchDirectoryCustomTextBox.setGeometry(QtCore.QRect(400, 240, 231, 31))
        self.searchDirectoryCustomTextBox.setInputMask(_fromUtf8(""))
        self.searchDirectoryCustomTextBox.setText(_fromUtf8(""))
        self.searchDirectoryCustomTextBox.setCursorPosition(0)
        self.searchDirectoryCustomTextBox.setPlaceholderText(_fromUtf8(""))
        self.searchDirectoryCustomTextBox.setObjectName(_fromUtf8("searchDirectoryCustomTextBox"))
        self.searchCheckBox = QtGui.QCheckBox(Form)
        self.searchCheckBox.setEnabled(True)
        self.searchCheckBox.setGeometry(QtCore.QRect(160, 240, 151, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        self.searchCheckBox.setFont(font)
        self.searchCheckBox.setIconSize(QtCore.QSize(12, 12))
        self.searchCheckBox.setCheckable(True)
        self.searchCheckBox.setChecked(True)
        self.searchCheckBox.setObjectName(_fromUtf8("searchCheckBox"))
        self.searchDirectoryLabel = QtGui.QLabel(Form)
        self.searchDirectoryLabel.setGeometry(QtCore.QRect(30, 240, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.searchDirectoryLabel.setFont(font)
        self.searchDirectoryLabel.setObjectName(_fromUtf8("searchDirectoryLabel"))
        self.searchBowseBtn = QtGui.QPushButton(Form)
        self.searchBowseBtn.setGeometry(QtCore.QRect(640, 240, 71, 29))
        self.searchBowseBtn.setObjectName(_fromUtf8("searchBowseBtn"))
        self.searchDirectoryCustomLabel = QtGui.QLabel(Form)
        self.searchDirectoryCustomLabel.setGeometry(QtCore.QRect(340, 240, 56, 31))
        self.searchDirectoryCustomLabel.setObjectName(_fromUtf8("searchDirectoryCustomLabel"))
        self.searchPatternLabel = QtGui.QLabel(Form)
        self.searchPatternLabel.setGeometry(QtCore.QRect(30, 310, 101, 31))
        self.searchPatternLabel.setObjectName(_fromUtf8("searchPatternLabel"))
        self.searchPAtternTextBox = QtGui.QLineEdit(Form)
        self.searchPAtternTextBox.setGeometry(QtCore.QRect(150, 310, 221, 31))
        self.searchPAtternTextBox.setObjectName(_fromUtf8("searchPAtternTextBox"))
        self.helpBtn = QtGui.QPushButton(Form)
        self.helpBtn.setGeometry(QtCore.QRect(380, 310, 90, 29))
        self.helpBtn.setObjectName(_fromUtf8("helpBtn"))
        self.sortBtn = QtGui.QPushButton(Form)
        self.sortBtn.setGeometry(QtCore.QRect(180, 380, 121, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Slab"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sortBtn.setFont(font)
        self.sortBtn.setStyleSheet(_fromUtf8("background-color:rgba(57, 114, 171, 100);\n"
"border: 2px solid rgba(125, 125, 125, 150);\n"
"border-radius: 25px;"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons8-play-filled-100.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sortBtn.setIcon(icon1)
        self.sortBtn.setObjectName(_fromUtf8("sortBtn"))
        self.clearAllBtn = QtGui.QPushButton(Form)
        self.clearAllBtn.setGeometry(QtCore.QRect(40, 390, 101, 29))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons8-clear-symbol-96.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearAllBtn.setIcon(icon2)
        self.clearAllBtn.setObjectName(_fromUtf8("clearAllBtn"))
        self.statusLabel = QtGui.QLabel(Form)
        self.statusLabel.setGeometry(QtCore.QRect(370, 380, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.statusInfoLabel = QtGui.QLabel(Form)
        self.statusInfoLabel.setGeometry(QtCore.QRect(370, 390, 311, 51))
        self.statusInfoLabel.setObjectName(_fromUtf8("statusInfoLabel"))
        self.statusInfoLabel.hide()
        self.progressBar = QtGui.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(20, 460, 711, 16))
        self.progressBar.hide()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet(_fromUtf8("border: 1px solid rgb(120, 120, 120, 150);"))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 80, 721, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.aboutBtn = QtGui.QToolButton(Form)
        self.aboutBtn.setGeometry(QtCore.QRect(680, 30, 41, 51))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons8-about-96 (1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutBtn.setIcon(icon3)
        self.aboutBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aboutBtn.setObjectName(_fromUtf8("aboutBtn"))
        
        self.targetBrowseBtn.hide()
        self.targetDirectoryCustomLabel.hide()
        self.tagetDirectoryCustomTextBox.hide()

        self.searchBowseBtn.hide()
        self.searchDirectoryCustomLabel.hide()
        self.searchDirectoryCustomTextBox.hide()
            
        self.retranslateUi(Form)

        QtCore.QObject.connect(self.targetCheckBox, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), self.target_checkbox)
        QtCore.QObject.connect(self.searchCheckBox, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), self.search_checkbox)
        QtCore.QObject.connect(self.sortBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.start)
        QtCore.QObject.connect(self.clearAllBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.clear_all)
        QtCore.QObject.connect(self.targetBrowseBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.target_browse)
        QtCore.QObject.connect(self.searchBowseBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.search_browse)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Show Sort.", None))
        self.headerLabel.setText(_translate("Form", "Show Sort.", None))
        self.headerCaptionText.setText(_translate("Form", "Sorting TV Shows made effortless...", None))
        self.versionLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#990000;\">1.0</span></p></body></html>", None))
        self.titleTextBox.setPlaceholderText(_translate("Form", "  eg: Breaking Bad", None))
        self.titleLabel.setText(_translate("Form", "<html><head/><body><p>Show Title</p></body></html>", None))
        self.targetDirectoryLabel.setText(_translate("Form", "Target Directory :", None))
        self.targetCheckBox.setText(_translate("Form", "Present Directory", None))
        self.targetBrowseBtn.setText(_translate("Form", "Browse", None))
        self.targetDirectoryCustomLabel.setText(_translate("Form", "Custom:", None))
        self.searchCheckBox.setText(_translate("Form", "Present Directory", None))
        self.searchDirectoryLabel.setText(_translate("Form", "Search Directory : ", None))
        self.searchBowseBtn.setText(_translate("Form", "Browse", None))
        self.searchDirectoryCustomLabel.setText(_translate("Form", "Custom:", None))
        self.searchPatternLabel.setText(_translate("Form", "Search Pattern:", None))
        self.searchPAtternTextBox.setPlaceholderText(_translate("Form", "  eg: Breaking Bad S(**)E(**) ", None))
        self.helpBtn.setText(_translate("Form", "Help!", None))
        self.sortBtn.setText(_translate("Form", "Sort.", None))
        self.clearAllBtn.setText(_translate("Form", "Clear All", None))
        self.statusLabel.setText(_translate("Form", "Status:", None))
        self.statusInfoLabel.setText(_translate("Form", "Status Info!", None))
        self.progressBar.setFormat(_translate("Form", "%p% Completed", None))
        self.aboutBtn.setText(_translate("Form", "About", None))

    def target_checkbox(self, state):
        if state == QtCore.Qt.Checked:
            self.targetBrowseBtn.hide()
            self.targetDirectoryCustomLabel.hide()
            self.tagetDirectoryCustomTextBox.hide()
            self.tagetDirectoryCustomTextBox.setText("")
        else:
            self.targetBrowseBtn.show()
            self.targetDirectoryCustomLabel.show()
            self.tagetDirectoryCustomTextBox.show()

    def search_checkbox(self, state):
        if state == QtCore.Qt.Checked:
            self.searchBowseBtn.hide()
            self.searchDirectoryCustomLabel.hide()
            self.searchDirectoryCustomTextBox.hide()
            self.searchDirectoryCustomTextBox.setText("")
        else:
            self.searchBowseBtn.show()
            self.searchDirectoryCustomLabel.show()
            self.searchDirectoryCustomTextBox.show()

    def clear_all(self):
        self.searchDirectoryCustomTextBox.clear()
        self.tagetDirectoryCustomTextBox.clear()
        self.titleTextBox.clear()
        self.searchPAtternTextBox.clear()
        self.statusInfoLabel.clear()

    def target_browse(self):
        path = QtGui.QFileDialog.getExistingDirectory()
        self.tagetDirectoryCustomTextBox.setText(path)

    def search_browse(self):
        path = QtGui.QFileDialog.getExistingDirectory()
        self.searchDirectoryCustomTextBox.setText(path)

    def start(self):
        self.name = self.titleTextBox.text()
        self.dirPath = self.searchDirectoryCustomTextBox.text()
        self.dest = self.tagetDirectoryCustomTextBox.text()
        self.pattern = self.searchPAtternTextBox.text()
        
        self.Show = Sort(self.dirPath, self.pattern, self.dest, self.name)
        
        if self.Show.start_operation() == True:
            self.statusInfoLabel.setText("Working...")
        else:
            self.statusInfoLabel.setText("That's an error: Invalid Search Directory!")
        self.statusInfoLabel.show()
        
        try:
            self.numfiles = self.Show.extract_data()
        except:
            self.statusInfoLabel.setText("That's an error: Invalid pattern!")
        
        if self.numfiles == 0:
            self.statusInfoLabel.setText("No matching files found!")
            self.progressBar.hide()
        else:
            self.statusInfoLabel.setText('Working...')
            try:
                self.sort()
            except:
                self.statusInfoLabel.setText("Error occured: Sorting failed!.")
            else:
                self.statusInfoLabel.setText("{} files processed successfully".format(self.numfiles+1))
    
    def sort(self):
        currentProgress = 0
        self.progressBar.show()
        for season, episodes in sorted(self.Show.dataShelve.items()):
            for ep, path in sorted(episodes.items()):
                destDir = os.path.join(self.Show.dest, self.Show.showName, "Season {}".format(season))
                if not os.path.exists(destDir):
                    os.makedirs(destDir)
                shutil.move(path, os.path.join(destDir, "Episode {}{}".format(ep, os.path.splitext(path)[1])))
                currentProgress += 1
                self.progressBar.setValue((currentProgress/self.numfiles)*100)
        

import Resources.ShowSortResources_rc
from Resources.ShowSortBase import Sort
import os
import shutil